# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('discount_code', models.CharField(blank=True, default='', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shipped', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='customers.Customer')),
            ],
        ),
    ]
