# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170415_1656'),
        ('customers', '0002_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.Purchase')),
            ],
        ),
    ]
