# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170415_1656'),
        ('customers', '0003_purchasitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Purchase')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasitem',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='PurchasItem',
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(through='customers.PurchaseItem', to='products.Product'),
        ),
    ]
