# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20170506_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
