# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20170506_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
