# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('location', models.CharField(max_length=10, unique=True)),
                ('serial_number', models.CharField(max_length=40, unique=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
