# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 19:59
from __future__ import unicode_literals

from django.db import migrations
from django.db import IntegrityError


def forwards(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    for category_name in ['Books', 'Videos', 'Shirts', 'Toys']:
        try:
            Category.objects.create(name=category_name)
        except IntegrityError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170415_1656'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
