# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Everywhere'), (2, 'Category-only')], default=0),
        ),
    ]
